"""testing adding via models

Revision ID: 4882c36311a8
Revises: 3c3bacd7b690
Create Date: 2025-07-01 13:20:57.086879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4882c36311a8'
down_revision: Union[str, Sequence[str], None] = '3c3bacd7b690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('id_test', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'id_test')
    # ### end Alembic commands ###
